# docker-compose.yml
# 2025-10-01
# Author: Xuan Tuan Minh Nguyen
# This file is used to start the database for the project

version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
